import uuid

from sqlalchemy import Boolean, Date, Float, ForeignKey, String, Text, TIMESTAMP
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

import datetime

from .base import Base


class LateFusionReport(Base):
    __tablename__ = "late_fusion_reports"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    report_period_start: Mapped[datetime.date] = mapped_column(Date, nullable=False)
    report_period_end: Mapped[datetime.date] = mapped_column(Date, nullable=False)

    # e.g. "Stable" | "At Risk" | "Declining" | "Crisis"
    prediction_label: Mapped[str] = mapped_column(String(50), nullable=False)

    # Narrative generated by the fusion model for the user
    qualitative_report: Mapped[str] = mapped_column(Text, nullable=False)

    is_crisis_flagged: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # MHI score: 0.0 (Crisis) → 1.0 (Stable)  Formula: 1.0 - clamp(avg_rp/100, 0, 1)
    numerical_health_index: Mapped[float] = mapped_column(Float, nullable=False)

    fusion_algorithm_version: Mapped[str] = mapped_column(
        String(20), default="v1.0.0", nullable=False
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        TIMESTAMP(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships 
    user: Mapped["User"] = relationship("User", back_populates="fusion_reports") # type: ignore[name-defined]

    def __repr__(self) -> str:
        return (
            f"<LateFusionReport id={self.id} mhi={self.numerical_health_index:.2f} "
            f"crisis={self.is_crisis_flagged}>"
        )